server:
  port: 8088
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:todo
    username: jenkincs
    password: jenkincs@@
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
